import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { Provider } from 'react-redux';
import store from './redux/store';
import StoreProvider from "./redux/storeProvider";
import { Fragment } from "react";
import HeaderModal from "./components/headerModal";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// export const revalidate = process.env.NEXT_PUBLIC_REVALIDATE ? +process.env.NEXT_PUBLIC_REVALIDATE : 60;
// export const dynamicParams = true;

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={comfortaa.className}>
                <StoreProvider>
                    <Fragment>
                        <HeaderModal />
                        <Header />
                        {children}
                    </Fragment >
                </StoreProvider>
            </body>
        </html >
    );
}
