import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import StoreProvider from "./redux/storeProvider";
import { Fragment } from "react";
import HeaderModal from "./components/headerModal";
import { getSession } from "@auth0/nextjs-auth0";

const comfortaa = Comfortaa({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getSession();
    const initialUser = session ? session.user : null;
    return (
        <html lang="en">
            <body className={comfortaa.className}>
                <StoreProvider initialUser={initialUser}>
                    <Fragment>
                        <HeaderModal />
                        <Header />
                        {children}
                    </Fragment>
                </StoreProvider>
            </body>
        </html>
    );
}
